export const environment = {
  production: false,
  beta: true,
  MATOMO_URL: 'https://providers.eosc-portal.eu/matomo/',
  MATOMO_SITE: 2,
  FAQ_ENDPOINT: '/faq/api',
  API_ENDPOINT: '/api',
  API_LOGIN: '/api/oauth2/authorization/google',
  STATS_ENDPOINT: 'https://beta.eosc-portal.eu/stats-api/',
  projectName: 'EOSC',
  projectMail: 'onboarding@eosc-portal.eu',
  serviceORresource: 'Service',
  hasUserConsent: true,
  privacyPolicyURL: './comingSoon',
  onboardingAgreementURL: './comingSoon',
  marketplaceServicesURL: './comingSoon',
  marketplaceDatasourcesURL: './comingSoon',
  marketplaceTrainingResourcesURL: './comingSoon',
  API_TOKEN_ENDPOINT: 'https://aai.eosc-portal.eu/providers-api',
  INSIGHTS_ENDPOINT: 'provider_insights_api/v1/statistics/rs',
  AUTOCOMPLETION_ENDPOINT: 'v1/auto_completion',
  showHelpContent: false,
  MONITORING_URL: './comingSoon'
};
