export const environment = {
  production: true,
  beta: false,
  MATOMO_URL: 'https://providers.eosc-portal.eu/matomo/',
  MATOMO_SITE: 1,
  FAQ_ENDPOINT: '/faq/api',
  API_ENDPOINT: '/api',
  STATS_ENDPOINT: 'https://providers.eosc-portal.eu/stats-api/',
  projectName: 'EOSC',
  projectMail: 'onboarding@eosc-portal.eu',
  serviceORresource: 'Service',
  hasUserConsent: true,
  privacyPolicyURL: 'https://www.eosc-portal.eu/privacy-policy-summary',
  onboardingAgreementURL: 'https://wiki.eoscfuture.eu/display/PUBLIC/EOSC+Catalogue+Onboarding+Agreement+and+Workflow',
  marketplaceServicesURL: 'https://marketplace.eosc-portal.eu/services/',
  marketplaceDatasourcesURL: 'https://marketplace.eosc-portal.eu/services/',
  marketplaceTrainingResourcesURL: 'https://search.eosc-portal.eu/trainings/',
  API_TOKEN_ENDPOINT: 'https://aai.eosc-portal.eu/providers-api',
  INSIGHTS_ENDPOINT: 'provider_insights_api/v1/statistics/rs',
  AUTOCOMPLETION_ENDPOINT: 'v1/auto_completion',
  showHelpContent: false,
  MONITORING_URL: 'https://eosc.ui.argo.grnet.gr'
};
