export const environment = {
  production: false,
  beta: true,
  MATOMO_URL: 'https://providers.eosc-portal.eu/matomo/',
  MATOMO_SITE: 2,
  FAQ_ENDPOINT: '/faq/api',
  API_ENDPOINT: '/api',
  STATS_ENDPOINT: 'https://beta.eosc-portal.eu/stats-api/',
  projectName: 'EOSC',
  projectMail: 'onboarding@eosc-portal.eu',
  serviceORresource: 'Service',
  hasUserConsent: true,
  privacyPolicyURL: 'https://www.eosc-portal.eu/privacy-policy-summary',
  onboardingAgreementURL: 'https://wiki.eoscfuture.eu/display/PUBLIC/EOSC+Catalogue+Onboarding+and+Onboarding+Agreement',
  marketplaceServicesURL: 'https://beta.marketplace.eosc-portal.eu/services/',
  marketplaceDatasourcesURL: 'https://beta.marketplace.eosc-portal.eu/datasources/',
  marketplaceTrainingResourcesURL: 'https://search.eosc-portal.eu/trainings/',
  API_TOKEN_ENDPOINT: 'https://aai.eosc-portal.eu/providers-api',
  showHelpContent: false
};
