export const environment = {
  production: false,
  beta: true,
  MATOMO_URL: 'https://providers.eosc-portal.eu/matomo/',
  MATOMO_SITE: 2,
  FAQ_ENDPOINT: '/faq/api',
  API_ENDPOINT: '/api',
  API_LOGIN: '/api/oauth2/authorization/eosc',
  API_LOGOUT: '/api/logout',
  STATS_ENDPOINT: 'https://beta.eosc-portal.eu/stats-api/',
  projectName: 'EOSC',
  projectMail: 'support@sandbox.eosc-beyond.eu',
  serviceORresource: 'Service',
  hasUserConsent: true,
  privacyPolicyURL: 'https://docs.google.com/document/d/10fhcpZ7jngLM6VVTLLMXDN1QoVE3Jvoq4RF8NeYydSA/edit?tab=t.0#heading=h.kp1upoc0eymv',
  onboardingAgreementURL: './comingSoon',
  marketplaceServicesURL: './comingSoon',
  marketplaceDatasourcesURL: './comingSoon',
  marketplaceTrainingResourcesURL: './comingSoon',
  API_TOKEN_ENDPOINT: 'https://core-proxy.sandbox.eosc-beyond.eu/providers-api/',
  INSIGHTS_ENDPOINT: 'provider_insights_api/v1/statistics/rs',
  AUTOCOMPLETION_ENDPOINT: 'v1/auto_completion',
  showHelpContent: false,
  MONITORING_URL: './comingSoon',
  WS_ENDPOINT: ''
};
