export const environment = {
  production: true,
  beta: false,
  CATALOGUE: 'eosc',
  FAQ_ENDPOINT: '/faq/api',
  API_ENDPOINT: '/api',
  API_LOGIN: '/api/oauth2/authorization/eosc',
  API_LOGOUT: '/api/logout',
  STATS_ENDPOINT: 'https://providers.eosc-portal.eu/stats-api/',
  serviceORresource: 'Service',
  hasUserConsent: true,
  privacyPolicyURL: 'assets/files/Privacy Policy – EOSC Innovation Sandbox -Service Catalogue.pdf',
  onboardingAgreementURL: './comingSoon',
  marketplaceServicesURL: './comingSoon',
  marketplaceDatasourcesURL: './comingSoon',
  marketplaceTrainingResourcesURL: './comingSoon',
  API_TOKEN_ENDPOINT: 'https://core-proxy.sandbox.eosc-beyond.eu/providers-api/',
  INSIGHTS_ENDPOINT: 'provider_insights_api/v1/statistics/rs',
  AUTOCOMPLETION_ENDPOINT: 'v1/auto_completion',
  MONITORING_URL: './comingSoon',
  WS_ENDPOINT: ''
};
