export class Description {
    desc: string;
    label: string;
    mandatory?: boolean;
    recommended?: boolean;
}
export const urlDesc = {label: 'url', mandatory: true, desc: 'Link to a url providing information about the service. This url is usually hosted and maintained by the service providers. It contains fresh and additional information, such as what APIs are supported or links to the documentation'};
export const nameDesc = {label: 'name', mandatory: true, desc: 'Brief marketing name of service as assigned by the service providers. Should be descriptive from a customer point of view, and should be quite simple, such that someone non-technical is able to understand what the service is about'};
export const taglineDesc = {label: 'tagline', mandatory: false, desc: 'Catchline or slogan of service for marketing/advertising purposes.'};
export const descriptionDesc = {label: 'description', mandatory: true, desc: 'High-level description of what the service does in terms of functionality it provides and the resources it enables access to. Should be similar to the name described above, and should cover the value provided by the service, in fairly non-technical terms. These descriptions may seem obvious but help everyone within the organization understand the service, and also will be needed for the Service Catalogue, which will be shown to users and customers. It may provide also information related to the offered capacity, number of installations, underlying data that is offered'};
export const optionsDesc = {label: 'options', mandatory: false, desc: 'High-level description of the various options or forms in which the service/resource can be instantiated.'};
export const targetUsersDesc = {label: 'target users', mandatory: true, desc: 'Type of users/customers that commissions a service/resource provider to deliver a service.'};
export const userValueDesc = {label: 'user value', mandatory: false, desc: 'The benefit to a customer and their users delivered by the service. Benefits are usually related to alleviating pains (e.g., eliminate undesired outcomes, obstacles or risks) or producing gains (e.g. increased performance, social gains, positive emotions or cost saving)'};
export const userBaseDesc = {label: 'user base ', mandatory: false, desc: 'List of customers, communities, etc using the service'};
export const useCasesDesc = {label: 'use case', mandatory: false, desc: 'List of use cases supported by this service/resource.'};
export const logoDesc = {label: 'logo', mandatory: true, desc: 'Link to a visual representation for the service. If none exists, providers are urged to use the organization\'s logo'};
export const multimediaURLDesc = {label: 'multimedia URL', mandatory: false, desc: 'Link to a page containing multimedia regarding the service'};
export const providersDesc = {label: 'providers', mandatory: true, desc: 'Organisation that manages and delivers the service and with whom the customer signs the SLA'};
export const versionDesc = {label: 'version', mandatory: false, desc: 'Informs about the implementation of the service that is in force as well as about its previous implementations, if any'};
export const lastUpdateDesc = {label: 'date of Last Update', mandatory: false, desc: 'The date of the latest update'};
export const changeLogDesc = {label: 'change Log', mandatory: false, desc: 'Summary of the service/resource features updated from the previous version.'};
export const certificationsDesc = {label: 'certifications', mandatory: false, desc: 'List of certifications obtained for the service from independent third parties.'};
export const standardsDesc = {label: 'standards', mandatory: false, desc: 'List of standards supported by the service.'};
export const validForDesc = {label: 'valid Until', mandatory: false, desc: 'The date up to which the service description is valid'};
export const phaseDesc = {label: 'lifeCycleStatus', mandatory: true, desc: 'Is used to tag the service to the full service cycle: e.g., discovery, alpha (prototype available for closed set of users), beta (service being developed while available for testing publicly), production, retired (not anymore offered)'};
export const trlDesc = {label: 'trl', mandatory: true, desc: 'Is used to tag the service to the Technology Readiness Level'};
export const scientificDomainDesc = {label: 'scientific domain', mandatory: true, desc: 'The branch of science, scientific discipline that is related to the service/resource.'};
export const scientificSubDomainDesc = {label: 'scientific subdomain', mandatory: true, desc: 'The subbranch of science, scientific subdicipline that is related to the service/resource.'};
export const superCategoryDesc = {label: 'supercategory', mandatory: true, desc: 'A named group for a predefined list of categories.'};
export const categoryDesc = {label: 'category', mandatory: true, desc: 'A named group of services/resources that offer access to the same type of resource or capabilities.'};
export const subcategoryDesc = {label: 'subcategory', mandatory: true, desc: 'A named group of services/resources that offer access to the same type of resource or capabilities, within the defined service category'};
export const languagesDesc = {label: 'languages', mandatory: true, desc: 'List of languages in which the service is available'};
export const placesDesc = {label: 'places', mandatory: true, desc: 'List of countries within which the service is available'};
export const accessTypesDesc = {label: 'access types', mandatory: false, desc: 'The way a user can access the service/resource (Remote, Physical, Virtual, etc.)'};
export const accessModesDesc = {label: 'access modes', mandatory: false, desc: 'The mode a user can access the service/resource (Excellence Driven, Market driven, etc)'};
export const fundersDesc = {label: 'funded by', mandatory: false, desc: 'Sources of funding for the development and/or operation of the service.'};
export const tagsDesc = {label: 'tags', mandatory: false, desc: 'Field to facilitate searching based on keywords'};
export const requiredServicesDesc = {label: 'required Services', mandatory: false, desc: 'Other services that are required with this service'};
export const relatedServicesDesc = {label: 'related Services', mandatory: false, desc: 'Other services that are commonly used with this service'};
export const orderTypeDesc = {label: 'order type', mandatory: true, desc: 'Described id the service/resource can be accessed with an ordering process.'};
export const orderDesc = {label: 'order', mandatory: false, desc: 'URL for requesting the service from the service providers'};
export const helpdeskDesc = {label: 'helpdesk', mandatory: false, desc: 'The URL to a webpage with the contact person or helpdesk to ask more information from the service/resource provider about this service.'};
export const manualDesc = {label: 'user Manual', mandatory: false, desc: 'URL for the user manual and documentation'};
export const trainingDesc = {label: 'Training', mandatory: false, desc: 'URL for training information'};
export const monitoringDesc = {label: 'monitoring', mandatory: false, desc: 'URL for monitoring information about this service'};
export const maintenanceDesc = {label: 'maintenance', mandatory: false, desc: 'URL for information about planned maintenance windows for this service'};
export const pricingDesc = {label: 'pricing', mandatory: false, desc: 'URL of the page with payment models that apply, the cost in Euros and any restrictions that may apply.'};
export const serviceLevelAgreementDesc = {label: 'Service Level Agreement', mandatory: false, desc: 'URL of the page containing information about the levels of performance that a service providers is expected to achieve. Current service agreements (SLAs) available for the service or basis for a new SLA. These should be agreements with users (not providers)'};
export const termsOfUseDesc = {label: 'terms Of Use', mandatory: false, desc: 'URL of the webpage describing the rules, service/resource conditions and usage policy which one must agree to abide by in order to use the service.'};
export const privacyPolicyDesc = {label: 'Privacy Policy', mandatory: false, desc: 'URL to the privacy policy applicable to the service.'};
export const accessPolicyDesc = {label: 'Access Policy', mandatory: false, desc: 'URL to the information about the access policies that apply.'};
export const paymentModelDesc = {label: 'Payment Model', mandatory: false, desc: 'URL with the supported payment models and restrictions that apply to each of them.'};
export const fundingDesc = {label: 'funding Sources', mandatory: false, desc: 'Sources of funding for the development and operation of the service'};
export const ownerNameDesc = {label: 'owner name', mandatory: false, desc: 'Name of the person who has accountability for the whole service/resource from a management point of view.'};
export const ownerContactDesc = {label: 'owner contact', mandatory: false, desc: 'E-mail contact of the service/resource owner.'};
export const supportNameDesc = {label: 'support name', mandatory: false, desc: 'Name of the person to request technical/ operational support.'};
export const supportContactDesc = {label: 'support contact', mandatory: false, desc: 'E-mail contact of the person to request technical/ operational support.'};
export const securityNameDesc = {label: 'security name', mandatory: false, desc: 'Name of the person responsible for the security aspects of the service/resource.'};
export const securityContactDesc = {label: 'security contact', mandatory: false, desc: 'Contact of the person responsible for the security aspects of the service/resource.'};

// option class fields
export const optionsNameDesc = {label: 'name', mandatory: true, desc: 'Name of the service/resource option.'};
export const optionsURLDesc = {label: 'url', mandatory: true, desc: 'Webpage with information about the service/resource option.'};
export const optionsDescriptionDesc = {label: 'description', mandatory: true, desc: 'The description of the service/resource option.'};
export const optionsLogoDesc = {label: 'logo', mandatory: false, desc: 'Link to the logo/visual identity of the service/resource provider.'};

// new service provider form fields
export const organizationNameDesc = {label: 'Name of your service provider', mandatory: true, desc: 'Name of the service/resource provider.'};
export const organizationIdDesc = {label: 'Choose an id for your service provider, this cannot be changed later', mandatory: true, desc: 'e.g. openaire, egi etc (a short id without spaces).'};
export const organizationWebsiteDesc = {label: 'The website of your organisation', mandatory: true, desc: 'Webpage with information about the service/resource provider. Note, Include \'http://\' or \'https://\' to the url.'};
export const providerDescriptionDesc = {label: 'Description', mandatory: true, desc: 'The description of the service/resource provider.'};
export const contactTelDesc = {label: 'Provide a telephone number', mandatory: true, desc: 'Telephone of the main contact person of the service/resource provider.'};
export const contactNameDesc = {label: 'Provide a contact name', mandatory: true, desc: 'Name of the main contact person of the service/resource provider.'};
export const contactEmailDesc = {label: 'Provide a contact email', mandatory: true, desc: 'Email of the main contact person of the service/resource provider.'};
export const logoUrlDesc = {label: 'Logo Url', mandatory: true, desc: 'Link to the logo/visual identity of the service/resource provider. Note, Include \'https://\' to the url.'};
export const firstNameDesc = {label: 'First name', mandatory: true, desc: ''};
export const lastNameDesc = {label: 'Last name', mandatory: true, desc: ''};
export const emailDesc = {label: 'Email address', mandatory: true, desc: ''};
